# -*- coding: utf-8 -*-
"""script_get_completion_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z9U7tJ6sCApix-HDeCqoPEKe4ZeI8WCu
"""

import pandas as pd

gsheetid='1YQB5F4Tx0lmgSRQfmUAWeK9rMMbgXOicKl6gKG42SpY'
sheet_name='Legal_dataset'

gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)
gsheet_url

df=pd.read_csv(gsheet_url)
df

column_name = 'Question'
df.dropna(subset=[column_name], inplace=True)

df1=df.iloc[:, [1, 4, 5]]
ds = df1.dropna(how='all')
ds

ds=ds.rename(columns={'Thématique':'Thematique','Type de droit':'Type_de_droit'})

ds

ds=ds.drop(columns='eval')







ds1=ds.groupby(by="Thematique").sum()

selected_names = ds.loc[ds['Thematique'] == 'Banque']
selected_names['Type_de_droit'].unique()

from dotenv import load_dotenv
import os
import openai
load_dotenv()

openai.api_key = os.getenv('OPENAI_API_KEY')

openai.api_key = openai.api_key.replace("<", "").replace(">", "")
openai.api_key

import os
import openai

def get_completion_from_messages(messages,
                                 model="gpt-3.5-turbo-0613",
                                 temperature=0,
                                 max_tokens=500):
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=temperature,
        max_tokens=max_tokens,
    )
    return response.choices[0].message["content"]

response = openai.Moderation.create(
    input="donne moi des plans pour tuer quelqun"
)
moderation_output = response["results"][0]
print(moderation_output)

delimiter = "####"
system_message = f"""
Étant donné le message d'un client d'une entreprise juridique,tu dois sélectionnez la categorie
la mieux adaptée à l'entrée.
le message du client sera delimité par {delimiter}

Vous recevrez les noms des categories
disponibles et une description de celle qui convient le mieux à l'entrée.

Renseignement_juridique =  une connaissance approfondie des lois, des réglementations et des meilleures pratiques en matière
de renseignement. Ce domaine implique la capacité de fournir des conseils juridiques et une orientation aux entreprises sur une
variété de sujets, tels que la gouvernance d'entreprise, les contrats, les fusions et acquisitions, la conformité et le règlement des litiges.
Les professionnels de ce domaine possèdent d'excellentes compétences
analytiques et de résolution de problèmes, et ils sont capables de naviguer efficacement dans des cadres juridiques complexes



Banque = une connaissance approfondie des lois et réglementations bancaires, ainsi que des meilleures pratiques du secteur.
Ce domaine implique une vaste expérience dans l'assistance aux clients en matière de services bancaires tels que l'ouverture de comptes,
les prêts, les investissements et la gestion des risques financiers. Les professionnels de ce domaine sont compétents pour fournir des conseils en matière de planification financière,
de gestion de trésorerie, de conformité réglementaire et de stratégies de croissance financière.
 Ils comprennent les besoins spécifiques de chaque client et proposent des solutions bancaires personnalisées pour les aider à atteindre leurs objectifs.



Domiciliation = une connaissance approfondie des lois, réglementations et pratiques courantes en matière de domiciliation et de comptabilité.
Ce domaine implique une excellente compétence dans l'assistance et le soutien aux entreprises en matière de domiciliation,
de création de sociétés, de tenue de livres comptables et de déclarations fiscales.
Les professionnels de ce domaine ont une expertise dans l'établissement de contrats de location et de baux commerciaux,
ainsi que dans la gestion des obligations légales et administratives liées à la domiciliation d'entreprises.
Ils fournissent des conseils précieux et une expertise stratégique à leurs clients pour les aider à atteindre leurs objectifs commerciaux en matière de domiciliation et de comptabilité.


Comptabilite = une connaissance approfondie des principes comptables, de fiscalité, de choix de fiscalité,
des normes financières et des meilleures pratiques en matière de comptabilité. Ce domaine implique une expérience étendue dans la tenue des livres comptables,
 l'établissement des états financiers, l'analyse des coûts et la gestion fiscale. Les professionnels de ce domaine sont compétents pour fournir des conseils en matière de gestion financière,
 d'optimisation fiscale et de conformité réglementaire aux entreprises et aux particuliers.
 Ils sont capables de comprendre les besoins financiers spécifiques de chaque client et de fournir des solutions personnalisées pour les aider à atteindre leurs objectifs financiers.

RAPPEL : la reponse DOIT être l'un des noms de consigne candidats spécifiés ci-dessus

voici quelques exemples de message et de la reponse demandée:


message=Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.
 Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?
reponse=Renseignement juridique

message= mutuelle prendre en tant que gérant non associé de la EURL, est ce assimilé salarié ou travailleur non salariés car sur certains sites, il est mentionné que gérant non associé est (assimilé salarié), merci d'avance
reponse=Renseignement juridique

message=quelles démarches à réaliser auprès de l'URSSAF
reponse=Renseignement juridique

message=Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?
reponse=Comptabilité

message=Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque
reponse=Banque

message= Bonjour, je souhaite changer le siège sociale de ma SARL. Actuellement domicilié dans le 92 à Sèvres, je compte déménager dans mon futur local. J'ai signé une promesse de vente sur ce local et j'ai une autorisation de domiciliation du propriétaire (qui détient le local en SCI). Je souhaite savoir cela est possible avant que je ne sois définitivement propriétaire ou si je dois attente d'être propriétaire?
reponse=Domiciliation

"""

user_message = f"""\
Je souhaiterais démissionner de ma société - en tant que Président, DG avec 51% des parts. Je suis prêt à démissionner sans vendre mes parts.

"""
messages =  [
{'role':'system',
 'content': system_message},
{'role':'user',
 'content': f"{delimiter}{user_message}{delimiter}"},
]
response = get_completion_from_messages(messages)
print(response)

def evaluation(x):
    delimiter = "####"
    system_message = f"""
    Étant donné le message d'un client d'une entreprise juridique,tu dois sélectionnez la categorie
    la mieux adaptée à l'entrée.
    le message du client sera delimité par {delimiter}

    Vous recevrez les noms des categories
    disponibles et une description de celle qui convient le mieux à l'entrée.

    Renseignement_juridique =  une connaissance approfondie des lois, des réglementations et des meilleures pratiques en matière
    de renseignement. Ce domaine implique la capacité de fournir des conseils juridiques et une orientation aux entreprises sur une
    variété de sujets, tels que la gouvernance d'entreprise, les contrats, les fusions et acquisitions, la conformité et le règlement des litiges.
    Les professionnels de ce domaine possèdent d'excellentes compétences
    analytiques et de résolution de problèmes, et ils sont capables de naviguer efficacement dans des cadres juridiques complexes



    Banque = une connaissance approfondie des lois et réglementations bancaires, ainsi que des meilleures pratiques du secteur.
    Ce domaine implique une vaste expérience dans l'assistance aux clients en matière de services bancaires tels que l'ouverture de comptes,
    les prêts, les investissements et la gestion des risques financiers. Les professionnels de ce domaine sont compétents pour fournir des conseils en matière de planification financière,
    de gestion de trésorerie, de conformité réglementaire et de stratégies de croissance financière.
    Ils comprennent les besoins spécifiques de chaque client et proposent des solutions bancaires personnalisées pour les aider à atteindre leurs objectifs.



    Domiciliation = une connaissance approfondie des lois, réglementations et pratiques courantes en matière de domiciliation et de comptabilité.
    Ce domaine implique une excellente compétence dans l'assistance et le soutien aux entreprises en matière de domiciliation,
    de création de sociétés, de tenue de livres comptables et de déclarations fiscales.
    Les professionnels de ce domaine ont une expertise dans l'établissement de contrats de location et de baux commerciaux,
    ainsi que dans la gestion des obligations légales et administratives liées à la domiciliation d'entreprises.
    Ils fournissent des conseils précieux et une expertise stratégique à leurs clients pour les aider à atteindre leurs objectifs commerciaux en matière de domiciliation et de comptabilité.


    Comptabilite = une connaissance approfondie des principes comptables, de fiscalité, de choix de fiscalité,
    des normes financières et des meilleures pratiques en matière de comptabilité. Ce domaine implique une expérience étendue dans la tenue des livres comptables,
    l'établissement des états financiers, l'analyse des coûts et la gestion fiscale. Les professionnels de ce domaine sont compétents pour fournir des conseils en matière de gestion financière,
    d'optimisation fiscale et de conformité réglementaire aux entreprises et aux particuliers.
    Ils sont capables de comprendre les besoins financiers spécifiques de chaque client et de fournir des solutions personnalisées pour les aider à atteindre leurs objectifs financiers.

    RAPPEL : la reponse DOIT être l'un des noms de consigne candidats spécifiés ci-dessus

    voici quelques exemples de message et de la reponse demandée:


    message=Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.
    Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?
    reponse=Renseignement juridique

    message=Bonjour, dans le cadre de l'ouverture de ma SASU, quels sont le domaine d'activité et les activités à sélectionner ? Je suis consultante en marketing et communication. Je vais également proposer des formations et des audit flash via mon site e commerce -> possibilité de commander un service et de l'acheter en ligne.
    reponse=Renseignement juridique

    message=Bonjour, j'aurai besoin d'un Kbis à jour. Pouvez vouez m'aider à m'en procurer un ? Merci
    reponse=Renseignement juridique

    message= mutuelle prendre en tant que gérant non associé de la EURL, est ce assimilé salarié ou travailleur non salariés car sur certains sites, il est mentionné que gérant non associé est (assimilé salarié), merci d'avance
    reponse=Renseignement juridique

    message=quelles démarches à réaliser auprès de l'URSSAF
    reponse=Renseignement juridique

    message=Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?
    reponse=Comptabilité

    message=SCI à l'IS assujettie ou non à la TVA ?
    reponse=Comptabilité

    message=Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque
    reponse=Banque

    message= Bonjour, je souhaite changer le siège sociale de ma SARL. Actuellement domicilié dans le 92 à Sèvres, je compte déménager dans mon futur local. J'ai signé une promesse de vente sur ce local et j'ai une autorisation de domiciliation du propriétaire (qui détient le local en SCI). Je souhaite savoir cela est possible avant que je ne sois définitivement propriétaire ou si je dois attente d'être propriétaire?
    reponse=Domiciliation



    """
    user_message=x.Question
    messages =  [
{'role':'system',
 'content': system_message},
{'role':'user',
 'content': f"{delimiter}{user_message}{delimiter}"},
]
    response = get_completion_from_messages(messages)
    evaluation= (response == x.Thematique)
    return evaluation

def evaluation(x):
    delimiter = "####"
    system_message = f"""
    Étant donné le message d'un client d'une entreprise juridique,tu dois sélectionnez la categorie
    la mieux adaptée à l'entrée.
    le message du client sera delimité par {delimiter}

    Vous recevrez les noms des categories
    disponibles et une description de celle qui convient le mieux à l'entrée.

    Renseignement_juridique =  une connaissance approfondie des lois, des réglementations et des meilleures pratiques en matière
    de renseignement. Ce domaine implique la capacité de fournir des conseils juridiques et une orientation aux entreprises sur une
    variété de sujets, tels que la gouvernance d'entreprise, les contrats, les fusions et acquisitions, la conformité et le règlement des litiges.
    Les professionnels de ce domaine possèdent d'excellentes compétences
    analytiques et de résolution de problèmes, et ils sont capables de naviguer efficacement dans des cadres juridiques complexes


    Banque = une connaissance approfondie des lois et réglementations bancaires, ainsi que des meilleures pratiques du secteur.
    Ce domaine implique une vaste expérience dans l'assistance aux clients en matière de services bancaires tels que l'ouverture de comptes,
    les prêts, les investissements et la gestion des risques financiers. Les professionnels de ce domaine sont compétents pour fournir des conseils en matière de planification financière,
    de gestion de trésorerie, de conformité réglementaire et de stratégies de croissance financière.
    Ils comprennent les besoins spécifiques de chaque client et proposent des solutions bancaires personnalisées pour les aider à atteindre leurs objectifs.



    Domiciliation = une connaissance approfondie des lois, réglementations et pratiques courantes en matière de domiciliation et de comptabilité.
    Ce domaine implique une excellente compétence dans l'assistance et le soutien aux entreprises en matière de domiciliation,
    de création de sociétés, de tenue de livres comptables et de déclarations fiscales.
    Les professionnels de ce domaine ont une expertise dans l'établissement de contrats de location et de baux commerciaux,
    ainsi que dans la gestion des obligations légales et administratives liées à la domiciliation d'entreprises.
    Ils fournissent des conseils précieux et une expertise stratégique à leurs clients pour les aider à atteindre leurs objectifs commerciaux en matière de domiciliation et de comptabilité.


    Comptabilite = une connaissance approfondie des principes comptables, de fiscalité, de choix de fiscalité,
    des normes financières et des meilleures pratiques en matière de comptabilité. Ce domaine implique une expérience étendue dans la tenue des livres comptables,
    l'établissement des états financiers, l'analyse des coûts et la gestion fiscale. Les professionnels de ce domaine sont compétents pour fournir des conseils en matière de gestion financière,
    d'optimisation fiscale et de conformité réglementaire aux entreprises et aux particuliers.
    Ils sont capables de comprendre les besoins financiers spécifiques de chaque client et de fournir des solutions personnalisées pour les aider à atteindre leurs objectifs financiers.

    RAPPEL : la reponse DOIT être l'un des noms de consigne candidats spécifiés ci-dessus suivie de {delimiter} et le message original du client

    voici quelques exemples de message et de la reponse demandée:


    message=Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?
    reponse=Renseignement juridique{delimiter}Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?{delimiter}

    message=Bonjour, dans le cadre de l'ouverture de ma SASU, quels sont le domaine d'activité et les activités à sélectionner ? Je suis consultante en marketing et communication. Je vais également proposer des formations et des audit flash via mon site e commerce -> possibilité de commander un service et de l'acheter en ligne.
    reponse=Renseignement juridique{delimiter}Bonjour, dans le cadre de l'ouverture de ma SASU, quels sont le domaine d'activité et les activités à sélectionner ? Je suis consultante en marketing et communication. Je vais également proposer des formations et des audit flash via mon site e commerce -> possibilité de commander un service et de l'acheter en ligne.{delimiter}


    message=Bonjour, j'aurai besoin d'un Kbis à jour. Pouvez vouez m'aider à m'en procurer un ? Merci
    reponse=Renseignement juridique{delimiter}Bonjour, j'aurai besoin d'un Kbis à jour. Pouvez vouez m'aider à m'en procurer un ? Merci{delimiter}


    message= mutuelle prendre en tant que gérant non associé de la EURL, est ce assimilé salarié ou travailleur non salariés car sur certains sites, il est mentionné que gérant non associé est (assimilé salarié), merci d'avance
    reponse=Renseignement juridique{delimiter}mutuelle prendre en tant que gérant non associé de la EURL, est ce assimilé salarié ou travailleur non salariés car sur certains sites, il est mentionné que gérant non associé est (assimilé salarié), merci d'avance{delimiter}


    message=quelles démarches à réaliser auprès de l'URSSAF
    reponse=Renseignement juridique{delimiter}quelles démarches à réaliser auprès de l'URSSAF{delimiter}

    message=Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?
    reponse=Comptabilité{delimiter}Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?{delimiter}


    message=SCI à l'IS assujettie ou non à la TVA ?
    reponse=Comptabilité{delimiter}SCI à l'IS assujettie ou non à la TVA ?{delimiter}

    message=Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque
    reponse=Banque{delimiter}Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque{delimiter}


    message= Bonjour, je souhaite changer le siège sociale de ma SARL. Actuellement domicilié dans le 92 à Sèvres, je compte déménager dans mon futur local. J'ai signé une promesse de vente sur ce local et j'ai une autorisation de domiciliation du propriétaire (qui détient le local en SCI). Je souhaite savoir cela est possible avant que je ne sois définitivement propriétaire ou si je dois attente d'être propriétaire?
    reponse=Domiciliation{delimiter}Bonjour, je souhaite changer le siège sociale de ma SARL. Actuellement domicilié dans le 92 à Sèvres, je compte déménager dans mon futur local. J'ai signé une promesse de vente sur ce local et j'ai une autorisation de domiciliation du propriétaire (qui détient le local en SCI). Je souhaite savoir cela est possible avant que je ne sois définitivement propriétaire ou si je dois attente d'être propriétaire?{delimiter}




    """
    user_message=x.Question
    messages =  [
{'role':'system',
 'content': system_message},
{'role':'user',
 'content': f"{delimiter}{user_message}{delimiter}"},
]
    response = get_completion_from_messages(messages)
    evaluation= (response == x.Thematique)
    return evaluation

len(ds)

ds_test=ds.iloc[25:50]
ds_test

evaluation(ds_test)

def thematique (x):
    def change_e(text):
        def replace_letter(word, index, new_letter):
            # Convert the word to a list of characters
            letters = list(word)
            letters[index] = new_letter
            new_word = ''.join(letters)
            return new_word

        for i in range(len(text)):
            if text[i]=='1':
                text=replace_letter(text,i,'e')
            if text[i]=="'":
                text=replace_letter(text,i,' ')
        return text

    def extract_thematique(x):
        types=['Renseignement juridique', 'Comptabilité', 'Banque','Droit social', 'Domiciliation']
        for type in types:
            if type.upper() in x.upper():

                return type

        return 'none'

    delimiter = "####"
    system_message = f"""
    Tu es un juriste competant ayant pour mission de classifier des messages clients .Étant donné le message d'un client d'une entreprise juridique,tu dois sélectionnez la categorie
    la mieux adaptée à l'entrée.
    le message du client sera delimité par {delimiter}

    suit les etapes suivantes precisement pour donner la bonne reponse

    etape 1:{delimiter} tu dois comprendre le message ,le reformuler en le resumant avec conservation de contexte


    etape 2:{delimiter} tu dois classifier le message en une des thematiques suivantes,voici une description de chaque categories

    Renseignement juridique : Cette catégorie concerne les demandes d'informations juridiques.
    Elle englobe des questions relatives aux lois, aux réglementations, aux droits et aux obligations légales.
     Les messages de cette catégorie peuvent être liés à des problèmes juridiques personnels,
     à des conseils pour la création d'une entreprise, à des contrats, à des litiges, etc.
    voici des examples ou tu dois choisir Renseignement juridique

    message=Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?
    reponse=Renseignement juridique{delimiter}Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?{delimiter}

    message=Bonjour, dans le cadre de l'ouverture de ma SASU, quels sont le domaine d'activité et les activités à sélectionner ? Je suis consultante en marketing et communication. Je vais également proposer des formations et des audit flash via mon site e commerce -> possibilité de commander un service et de l'acheter en ligne.
    reponse=Renseignement juridique{delimiter}Bonjour, dans le cadre de l'ouverture de ma SASU, quels sont le domaine d'activité et les activités à sélectionner ? Je suis consultante en marketing et communication. Je vais également proposer des formations et des audit flash via mon site e commerce -> possibilité de commander un service et de l'acheter en ligne.{delimiter}

    message=Bonjour, j'aurai besoin d'un Kbis à jour. Pouvez vouez m'aider à m'en procurer un ? Merci
    reponse=Renseignement juridique{delimiter}Bonjour, j'aurai besoin d'un Kbis à jour. Pouvez vouez m'aider à m'en procurer un ? Merci{delimiter}

    message= mutuelle prendre en tant que gérant non associé de la EURL, est ce assimilé salarié ou travailleur non salariés car sur certains sites, il est mentionné que gérant non associé est (assimilé salarié), merci d'avance
    reponse=Renseignement juridique{delimiter}mutuelle prendre en tant que gérant non associé de la EURL, est ce assimilé salarié ou travailleur non salariés car sur certains sites, il est mentionné que gérant non associé est (assimilé salarié), merci d'avance{delimiter}

    message=quelles démarches à réaliser auprès de l'URSSAF
    reponse=Renseignement juridique{delimiter}quelles démarches à réaliser auprès de l'URSSAF{delimiter}


    Banque :  Cette catégorie concerne les questions relatives aux services bancaires.
    Les messages de cette catégorie peuvent porter sur des demandes d'ouverture de compte, de prêts, de conseils en matière d'investissement,
    de gestion des finances personnelles, de transactions bancaires, de cartes de crédit, etc. Les requêtes sur les politiques bancaires,
    les taux d'intérêt, les garanties et les produits financiers peuvent également être classées dans cette catégorie.
    voici des examples ou tu dois choisir Banque

    message=Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque
    reponse=Banque{delimiter}Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque{delimiter}


    Domiciliation : Cette catégorie concerne les demandes liées à l'établissement ou à la gestion d'une adresse commerciale ou résidentielle.
    Les messages de cette catégorie peuvent porter sur des sujets tels que la location de bureaux, les services de réexpédition de courrier,
    la gestion des colis, les formalités administratives pour changer d'adresse, les services de conciergerie, etc.
    voici des examples ou tu dois choisir Domiciliation
    message= Bonjour, je souhaite changer le siège sociale de ma SARL. Actuellement domicilié dans le 92 à Sèvres, je compte déménager dans mon futur local. J'ai signé une promesse de vente sur ce local et j'ai une autorisation de domiciliation du propriétaire (qui détient le local en SCI). Je souhaite savoir cela est possible avant que je ne sois définitivement propriétaire ou si je dois attente d'être propriétaire?
    reponse=Domiciliation{delimiter}Bonjour, je souhaite changer le siège sociale de ma SARL. Actuellement domicilié dans le 92 à Sèvres, je compte déménager dans mon futur local. J'ai signé une promesse de vente sur ce local et j'ai une autorisation de domiciliation du propriétaire (qui détient le local en SCI). Je souhaite savoir cela est possible avant que je ne sois définitivement propriétaire ou si je dois attente d'être propriétaire?{delimiter}

    message=Pouvez vous me donner une estimation de ce que je gagne en faisant domicilier ma SASU à Paris plutôt qu'à mon domicile (Châtenay-Malabry 92290) ? Je fais du conseil en informatique, chiffre d'affaire autour de 150K€ par an.
    reponse=Domiciliation{delimiter}Pouvez vous me donner une estimation de ce que je gagne en faisant domicilier ma SASU à Paris plutôt qu'à mon domicile (Châtenay-Malabry 92290) ? Je fais du conseil en informatique, chiffre d'affaire autour de 150K€ par an.{delimiter}

    Comptabilité : Cette catégorie concerne les demandes liées à la comptabilité et à la gestion financière.
    Les messages de cette catégorie peuvent inclure des questions sur la tenue de livres, la déclaration fiscale,
    les normes comptables, les conseils en matière de gestion financière, les rapports financiers, les audits, etc.
    Les requêtes sur les logiciels de comptabilité et les outils de gestion financière peuvent également être classées dans cette catégorie.
    voici des examples ou tu dois choisir Comptabilité
    message=Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?
    reponse= Comptabilité {delimiter}Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?{delimiter}

    message=SCI à l'IS assujettie ou non à la TVA ?
    reponse=Comptabilité{delimiter}SCI à l'IS assujettie ou non à la TVA ?{delimiter}



    RAPPEL : la reponse DOIT être l'un des noms de consigne candidats spécifiés ci-dessus suivie de {delimiter} et le message original du client
    voici quelques exemples de message et de la reponse demandée:


    suit les etapes suivantes pour repondre
    etape 1:{delimiter}
    etape 2:{delimiter}


    """
    user_message = change_e(x)
    messages =  [
{'role':'system',
 'content': system_message},
{'role':'user',
 'content': f"{delimiter}{user_message}{delimiter}"},
]
    response = get_completion_from_messages(messages)

    return extract_thematique(response)

def extract_thematique(x):
    types=['Renseignement juridique', 'Comptabilité', 'Banque','Droit social', 'Domiciliation']
    for type in types:
        if type.upper() in x.upper():

            return type

    return 'none'

th=thematique(''' Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?''')
extract_thematique(th)

ds_test

ds_test.apply(thematique,axis=1)

def type_de_droit (x):
    def change_e(text):
        def replace_letter(word, index, new_letter):
            # Convert the word to a list of characters
            letters = list(word)
            letters[index] = new_letter
            new_word = ''.join(letters)
            return new_word
        for i in range(len(text)):
        if text[i]=='1':
            text=replace_letter(text,i,'e')
        if text[i]=="'":
            text=replace_letter(text,i,' ')
        return text
    delimiter = "####"
    system_message = f"""
    Étant donné un texte contenant une Thematique particulierele('Comptabilite','Domiciliation','Banque','Renseignement_juridique') et message d'un client d'une entreprise juridique .tu dois sélectionnez le type de droit
    concerné par a Thematique et le message
    le message du client sera delimité par {delimiter}

    Si la thematique est Renseignement_juridique tu dois choisir un des types de droits suivants
    Droit immobilier, Droit des sociétés, Droit commercial,Droit social, Autre, Droit des contrats,Droit de la propriété intellectuelle, Droit de la consommation,Droit fiscal


    Si la thematique est Domiciliation tu dois choisir un des types de droits suivants
    Droit des sociétés, Droit fiscal,Autre

    Si la thematique est Comptabilite tu dois choisir un des types de droits suivants
    Droit fiscal, Droit des sociétés

    Si la thematique est Banque tu dois choisir Autre



    RAPPEL : la reponse DOIT être l'un des types de droits mentionné si dessus

    voici quelques exemples de message et de la reponse demandée:


    texte=Renseignement juridique{delimiter}Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?{delimiter}
    reponse=Droit des sociétés

    texte=Renseignement juridique{delimiter} Bonjour j'ai actuellement une auto entreprise dans le domaine de la vente de puff ( cigarette electronique jetable). je souhaiterais changer de statut et passer en société pour ne plus avoir de restrictions de chiffre d'affaire etc. Mais pouvez vous m'éclairer sur la réglementation en france concernant les puffs car ces cigarettes électroniques jetables sont dans le viseur du gouvernenement en ce moment.{delimiter}
    reponse=Droit social

    texte=Renseignement juridique{delimiter}Comment sponsoriser nos employés au Maroc pour travailler en France{delimiter}
    reponse=Droit de la consommation

    texte=Renseignement juridique{delimiter}Je dois rediger un contrat un contrat pour un prestataire qui doit respecter certaines clauses que mon client m'impose{delimiter}
    reponse=Droit des contrats

    texte=Renseignement juridique{delimiter} Je suis victime d'une arnaque sur un site internet{delimiter}
    reponse=Droit commercial

    texte=Renseignement juridique{delimiter} quelles démarches à réaliser auprès de l'URSSAF{delimiter}
    reponse=Droit des sociétés

    texte=Comptabilité {delimiter}Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?{delimiter}
    reponse=Comptabilité

    texte=Comptabilité {delimiter}SCI à l'IS assujettie ou non à la TVA ?{delimiter}
    reponse=Droit fiscal

    texte=Banque {delimiter}Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque{delimiter}
    reponse= Autre

    texte= Domiciliation {delimiter}Dans le cadre de la création de ma SASU, j'ai choisi la domiciliation Legal Place cependant je serai en télétravail dans des lieux différents (à mon domicile par exemple (non exhaustif)). Est-ce que je dois cocher la case "Je vais exercer mon activité dans un lieu différent du siège social (magasin, bureau, atelier, non sédentaire, etc.)" dans " cas particulier" ?{delimiter}
    reponse=Autre





    """
    user_message = change_e(x)
    messages =  [
 {'role':'system',
 'content': system_message},
 {'role':'user',
 'content': f"{user_message}"},
 ]
    response = get_completion_from_messages(messages)

    return response

type_de_droit('Renseignement juridique####Je vais signer un accord de non-divulgation (NDA) pour collaborer avec un studio de capital-risque espagnol. Quel modèle recommandez-vous pour cela ?####')

def type_de_droit_1 (x):

    def change_e(text):
        def replace_letter(word, index, new_letter):
            # Convert the word to a list of characters
            letters = list(word)
            letters[index] = new_letter
            new_word = ''.join(letters)
            return new_word
        for i in range(len(text)):
            if text[i]=='1':
                text=replace_letter(text,i,'e')
            if text[i]=="'":
                text=replace_letter(text,i,' ')
        return text




    delimiter = "####"
    system_message = f"""
    tu es un juriste competent ayant comme mission de choisir quel type de droit correspond a un message
    suit les etapes suivantes pour choisir le bon type droit

    etape 1:{delimiter} extraire du message une thematique particuliere ('Comptabilite','Domiciliation','Banque','Renseignement_juridique')

    etape 2:{delimiter} tu est un juriste competent ,tu dois comprendre le reste du message du client delimité par {delimiter} et son sujet
    resume ensuite le message en le decrivant avec conservation do contexte

    etape 3:{delimiter} chaque thematique admet quelques type de droits qui lui corresponde,ta mission est de choisir le type de droit qui va le mieu
    avec le contexte du message


    la thematique Renseignement juridique admet les types de droits suivants:
    Droit immobilier : Le droit immobilier concerne les règles et les réglementations relatives à la propriété, à l'acquisition, à la gestion et à la vente de biens immobiliers. Il englobe des domaines tels que l'achat et la vente de biens immobiliers, la location, la copropriété, les baux commerciaux, les litiges fonciers et les réglementations de la construction.

    Droit des sociétés : Le droit des sociétés régit la création, la structure, le fonctionnement et la dissolution des sociétés commerciales. Il traite des questions telles que la formation de sociétés, les responsabilités des actionnaires, la gouvernance d'entreprise, les droits des actionnaires, les fusions et acquisitions, les contrats de société et les obligations légales des entreprises.
    Droit commercial : Le droit commercial concerne les activités commerciales et les transactions entre entreprises. Il englobe des aspects tels que les contrats commerciaux, les litiges commerciaux, les pratiques commerciales déloyales, la concurrence déloyale, la protection des consommateurs, la responsabilité civile et les réglementations commerciales spécifiques à certaines industries.
    Droit social : Le droit social, également connu sous le nom de droit du travail, concerne les relations entre employeurs et employés. Il comprend des domaines tels que les contrats de travail, les conditions de travail, la sécurité et la santé au travail, les congés et les vacances, la discrimination au travail, les licenciements et les litiges entre employeurs et employés.
    Autre : La catégorie "Autre" peut inclure des domaines juridiques spécifiques qui ne sont pas mentionnés dans les catégories précédentes. Il peut s'agir, par exemple, du droit de la famille, du droit pénal, du droit administratif ou de tout autre domaine juridique spécialisé.
    Droit des contrats : Le droit des contrats régit les règles et les obligations liées à la formation, à l'interprétation et à l'exécution des contrats. Il englobe des aspects tels que la validité des contrats, les droits et les devoirs des parties contractantes, les vices du consentement, les clauses contractuelles, la résiliation des contrats et les litiges contractuels.
    Droit de la propriété intellectuelle : Le droit de la propriété intellectuelle concerne la protection des droits liés aux créations intellectuelles, telles que les inventions, les marques, les œuvres artistiques, les brevets, les droits d'auteur et les secrets commerciaux. Il vise à protéger et à réglementer l'utilisation, la reproduction et la distribution de ces créations.
    Droit de la consommation : Le droit de la consommation concerne la protection des droits et des intérêts des consommateurs dans leurs relations avec les fournisseurs de biens et de services. Il traite des questions telles que les pratiques commerciales trompeuses, les garanties des produits, les contrats de consommation, la responsabilité des fabricants et les recours des consommateurs en cas de litige.
    Droit fiscal : Le droit fiscal concerne les règles et les réglementations


    la thematique Domiciliation admet les types de droits suivants  :
    Droit des sociétés : Le droit des sociétés régit la création, la structure, le fonctionnement et la dissolution des sociétés commerciales. Il traite des questions telles que la formation de sociétés, les responsabilités des actionnaires, la gouvernance d'entreprise, les droits des actionnaires, les fusions et acquisitions, les contrats de société et les obligations légales des entreprises.
    Droit fiscal : Le droit fiscal concerne les règles et les réglementations
    Autre : La catégorie "Autre" peut inclure des domaines juridiques spécifiques qui ne sont pas mentionnés dans les catégories précédentes. Il peut s'agir, par exemple, du droit de la famille, du droit pénal, du droit administratif ou de tout autre domaine juridique spécialisé.



    la thematique Comptabilite admet les types de droits suivants:
    Droit des sociétés : Le droit des sociétés régit la création, la structure, le fonctionnement et la dissolution des sociétés commerciales. Il traite des questions telles que la formation de sociétés, les responsabilités des actionnaires, la gouvernance d'entreprise, les droits des actionnaires, les fusions et acquisitions, les contrats de société et les obligations légales des entreprises.
    Droit fiscal : Le droit fiscal concerne les règles et les réglementations


    la thematique  Banque n'admet que :
    Autre : La catégorie "Autre" peut inclure des domaines juridiques spécifiques qui ne sont pas mentionnés dans les catégories précédentes. Il peut s'agir, par exemple, du droit de la famille, du droit pénal, du droit administratif ou de tout autre domaine juridique spécialisé.


    voici quelques exemples de messages et de la bonne reponse :


    texte=Renseignement juridique{delimiter}Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?{delimiter}
    reponse=Droit des sociétés

    texte=Renseignement juridique{delimiter}Bonjour, dans le cadre d'une location via un bail professionnel, qui doit prendre le contrat eau et électricité ? est-ce le bailleur qui refacture ensuite les frais au réel via les charges ou est-ce le locataire ?{delimiter}
    reponse=Droit immobilier

    texte=Renseignement juridique{delimiter}Comment sponsoriser nos employés au Maroc pour travailler en France{delimiter}
    reponse=Droit social

    texte=Renseignement juridique{delimiter} Bonjour, Je suis le dirigeant d une SASU ( Mnemosys), qui est destinée a offrir un service Informatique pour les entreprises, j'ai pour cela un site web mnemosys.fr qui est en cours de création,Je souhaiterai développer également mon offre pour les particuliers, avec notamment un site web dedié example.fr, est-ce que lors de la facturation de ces clients, je dois forcement faire une facture au nom de mnemosys, ou bien est-ce que j ai le droit d utiliser un autre nom commercial ? et est-ce que pour cela il y a une demarche a effectuer ?Cordialement, {delimiter}
    reponse=Droit commercial

    texte=Renseignement juridique{delimiter} Bonjour j'ai actuellement une auto entreprise dans le domaine de la vente de puff ( cigarette electronique jetable). je souhaiterais changer de statut et passer en société pour ne plus avoir de restrictions de chiffre d'affaire etc. Mais pouvez vous m'éclairer sur la réglementation en france concernant les puffs car ces cigarettes électroniques jetables sont dans le viseur du gouvernenement en ce moment.{delimiter}
    reponse=Droit social

    texte=Renseignement juridique{delimiter}Comment sponsoriser nos employés au Maroc pour travailler en France{delimiter}
    reponse=Droit de la consommation

    texte=Renseignement juridique{delimiter}Je dois rediger un contrat un contrat pour un prestataire qui doit respecter certaines clauses que mon client m'impose{delimiter}
    reponse=Droit des contrats

    texte=Renseignement juridique{delimiter} Je suis victime d'une arnaque sur un site internet{delimiter}
    reponse=Droit commercial

    texte=Renseignement juridique{delimiter} quelles démarches à réaliser auprès de l'URSSAF{delimiter}
    reponse=Droit des sociétés

    texte=Comptabilité {delimiter}Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?{delimiter}
    reponse=Comptabilité

    texte=Comptabilité {delimiter}SCI à l'IS assujettie ou non à la TVA ?{delimiter}
    reponse=Droit fiscal

    texte=Banque {delimiter}Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque{delimiter}
    reponse= Autre

    texte= Domiciliation {delimiter}Dans le cadre de la création de ma SASU, j'ai choisi la domiciliation Legal Place cependant je serai en télétravail dans des lieux différents (à mon domicile par exemple (non exhaustif)). Est-ce que je dois cocher la case "Je vais exercer mon activité dans un lieu différent du siège social (magasin, bureau, atelier, non sédentaire, etc.)" dans " cas particulier" ?{delimiter}
    reponse=Autre

    suit le format suivant
    etape 1:{delimiter} <step 1 reasoning>
    etape 2:{delimiter} <step 2 reasoning>
    etape 3:{delimiter} <step 3 reasoning>




    """




    user_message= x
    messages =  [
{'role':'system',
 'content': system_message},
{'role':'user',
 'content': f"{user_message}"},
]
    response = get_completion_from_messages(messages)


    return response

def extract_type(x):
    types=['Droit immobilier', 'Droit des sociétés', 'Droit commercial','Droit social', 'Autre', 'Droit des contrats','Droit de la propriété intellectuelle', 'Droit de la consommation''Droit fiscal']
    for type in types:
        if type.upper() in x.upper():
            return type

    return 'none'

ex=type_de_droit_1("""Renseignement juridique#### Bonjour j'ai actuellement une auto entreprise dans le domaine de la vente de puff ( cigarette electronique jetable). je souhaiterais changer de statut et passer en société pour ne plus avoir de restrictions de chiffre d'affaire etc. Mais pouvez vous m'éclairer sur la réglementation en france concernant les puffs car ces cigarettes électroniques jetables sont dans le viseur du gouvernenement en ce moment####""")
print(ex)
print(extract(ex))

def type_de_droit_2 (x):
    delimiter = "####"
    system_message = f"""
    Follow these steps to answer the customer queries.
    The customer query will be delimited with four hashtags,\
    i.e. {delimiter}.

    etape 1:{delimiter} extraire du message une thematique particuliere ('Comptabilite','Domiciliation','Banque','Renseignement_juridique')



    Step 2:{delimiter} tu est un juriste competent ,tu dois comprendre le message du client delimité par {delimiter} et son sujet le plus precisement possible   puis pour chaque thematique
    tu dois choisir le seul type de droit qui correspond

    Step 3:{delimiter} chaque thematique admet quelques type de droits qui lui corresponde
    la thematique Renseignement juridique admet les types de droits suivants:
    droit immobilier, Droit des sociétés, Droit commercial,Droit social, Autre, Droit des contrats,Droit de la propriété intellectuelle, Droit de la consommation,Droit fiscal


    la thematique Domiciliation admet les types de droits suivants  : Droit des sociétés, Droit fiscal,Autre

    la thematique Comptabilite admet les types de droits suivants: Droit fiscal, Droit des sociétés

    la thematique  Banque n'admet que 'Autre'

    suit ces etape pour repondre mais sans les ecrire
    etape 1:{delimiter} <step 1 reasoning>
    etape  2:{delimiter} <step 2 reasoning>
    etape  3:{delimiter} <step 3 reasoning>


    ta reponse finale ne dois pas depasser 3 mots,elle ne doit contenir que le type de droit correspendant
    voici quelques exemples de messages et de la bonne reponse :


    texte=Renseignement juridique{delimiter}Je suis en train de créer ma holding, et je voudrais que la SASU que je possède déjà soit 100% détenue par la holding.Mais dans le formulaire de création de la holding, je n'ai pas vu de point me permettant de saisir cette information. Comment faire?{delimiter}
    reponse=Droit des sociétés

    texte=Renseignement juridique{delimiter}Bonjour, dans le cadre d'une location via un bail professionnel, qui doit prendre le contrat eau et électricité ? est-ce le bailleur qui refacture ensuite les frais au réel via les charges ou est-ce le locataire ?{delimiter}
    reponse=Droit immobilier

    texte=Renseignement juridique{delimiter}Comment sponsoriser nos employés au Maroc pour travailler en France{delimiter}
    reponse=Droit social

    texte=Renseignement juridique{delimiter} Bonjour, Je suis le dirigeant d une SASU ( Mnemosys), qui est destinée a offrir un service Informatique pour les entreprises, j'ai pour cela un site web mnemosys.fr qui est en cours de création,Je souhaiterai développer également mon offre pour les particuliers, avec notamment un site web dedié example.fr, est-ce que lors de la facturation de ces clients, je dois forcement faire une facture au nom de mnemosys, ou bien est-ce que j ai le droit d utiliser un autre nom commercial ? et est-ce que pour cela il y a une demarche a effectuer ?Cordialement, {delimiter}
    reponse=Droit commercial

    texte=Renseignement juridique{delimiter} Bonjour j'ai actuellement une auto entreprise dans le domaine de la vente de puff ( cigarette electronique jetable). je souhaiterais changer de statut et passer en société pour ne plus avoir de restrictions de chiffre d'affaire etc. Mais pouvez vous m'éclairer sur la réglementation en france concernant les puffs car ces cigarettes électroniques jetables sont dans le viseur du gouvernenement en ce moment.{delimiter}
    reponse=Droit social

    texte=Renseignement juridique{delimiter}Comment sponsoriser nos employés au Maroc pour travailler en France{delimiter}
    reponse=Droit de la consommation

    texte=Renseignement juridique{delimiter}Je dois rediger un contrat un contrat pour un prestataire qui doit respecter certaines clauses que mon client m'impose{delimiter}
    reponse=Droit des contrats

    texte=Renseignement juridique{delimiter} Je suis victime d'une arnaque sur un site internet{delimiter}
    reponse=Droit commercial

    texte=Renseignement juridique{delimiter} quelles démarches à réaliser auprès de l'URSSAF{delimiter}
    reponse=Droit des sociétés

    texte=Comptabilité {delimiter}Bonjour, pour une SARL , l'associé minoritaire doit il obligatoirement être salarié dans les premiers mois de la création d'entreprise ?{delimiter}
    reponse=Comptabilité

    texte=Comptabilité {delimiter}SCI à l'IS assujettie ou non à la TVA ?{delimiter}
    reponse=Droit fiscal

    texte=Banque {delimiter}Je veux changer de banque pour mon compte pro et déposer le capital social et les statuts d l'entreprise dans une autre banque{delimiter}
    reponse= Autre

    texte= Domiciliation {delimiter}Dans le cadre de la création de ma SASU, j'ai choisi la domiciliation Legal Place cependant je serai en télétravail dans des lieux différents (à mon domicile par exemple (non exhaustif)). Est-ce que je dois cocher la case "Je vais exercer mon activité dans un lieu différent du siège social (magasin, bureau, atelier, non sédentaire, etc.)" dans " cas particulier" ?{delimiter}
    reponse=Autre

    """



    user_message=x.Thematique +"####"+ x.Question+"####"
    messages =  [
{'role':'system',
 'content': system_message},
{'role':'user',
 'content': f"{user_message}"},
]
    response = get_completion_from_messages(messages)


    return response

ds_test[:5]

ds_test[:5].apply(type_de_droit_2 , axis=1)

